In [1]:
import pandas as pd
import numpy as np
import scipy.stats as s

In [2]:
df=pd.read_csv("Exp2.csv")
df1=pd.read_csv("Exp2.csv")

In [3]:
#df.index=df.pop("dma")
df.pop("geoCode")
df1.pop("geoCode")

0     500
1     501
2     502
3     503
4     504
5     505
6     506
7     507
8     508
9     509
10    510
11    511
12    512
13    513
14    514
15    515
16    516
17    517
18    518
19    519
20    520
21    521
22    522
23    523
24    524
Name: geoCode, dtype: int64

In [4]:
df

,dma,2004+cancer,2004+cardiovascular,2004+stroke,2004+depression,2004+rehab,2004+vaccine,2004+diarrhea
0,Portland-Auburn ME,44,6,17,39,21,31,14
1,New York NY,47,6,13,38,16,33,12
2,Binghamton NY,48,3,16,50,12,37,24
3,Macon GA,44,14,14,37,19,49,14
4,Philadelphia PA,52,7,16,41,23,36,14
5,Detroit MI,47,6,16,45,14,31,15
6,Boston MA-Manchester NH,48,6,15,38,25,34,14
7,Savannah GA,43,11,17,37,28,43,10
8,Pittsburgh PA,51,10,17,50,23,34,16
9,Ft. Wayne IN,42,4,14,50,15,25,15
10,Cleveland-Akron (Canton) OH,42,6,16,44,18,26,14
11,Washington DC (Hagerstown MD),47,5,15,33,15,46,11
12,Baltimore MD,51,9,18,44,18,44,16
13,Flint-Saginaw-Bay City MI,43,8,17,50,12,34,19
14,Buffalo NY,49,5,20,49,18,25,16
15,Cincinnati OH,45,6,18,43,17,25,15
16,Erie PA,53,14,17,50,25,43,8
17,Charlotte NC,43,7,16,39,21,29,16
18,Greensboro-High Point-Winston Salem NC,47,10,15,45,24,29,13
19,Charleston SC,55,14,20,42,16,23,15
20,Augusta GA,48,12,26,39,18,24,14
21,Providence RI-New Bedford MA,43,3,16,45,20,36,17
22,Columbus GA,41,7,17,46,25,33,14
23,Burlington VT-Plattsburgh NY,49,6,14,53,21,44,10
24,Atlanta GA,42,6,15,35,19,36,13

In [5]:
arr=[]
for i in df:
    if(i=="dma"):
        continue
    else:
        arr.append(sum(df[i]))
df.loc[len(df.index)]=["Colomn total",arr[0],arr[1],arr[2],arr[3],arr[4],arr[5],arr[6]]
df1.loc[len(df1.index)]=["Colomn total",arr[0],arr[1],arr[2],arr[3],arr[4],arr[5],arr[6]]

In [6]:
df.index=df.pop("dma")
df1.index=df1.pop("dma")

In [7]:
sum(df.iloc[0])

172

In [8]:
arr=[]
for i in range(len(df.index)):
    arr.append(sum(df.iloc[i]))
rt=arr[-1]
arr.pop()
gt=sum(arr)
arr.append(gt)

In [9]:
df["Row total"]=arr
df1["Row total"]=arr

In [10]:
df

,2004+cancer,2004+cardiovascular,2004+stroke,2004+depression,2004+rehab,2004+vaccine,2004+diarrhea,Row total
dma,,,,,,,,
Portland-Auburn ME,44,6,17,39,21,31,14,172
New York NY,47,6,13,38,16,33,12,165
Binghamton NY,48,3,16,50,12,37,24,190
Macon GA,44,14,14,37,19,49,14,191
Philadelphia PA,52,7,16,41,23,36,14,189
Detroit MI,47,6,16,45,14,31,15,174
Boston MA-Manchester NH,48,6,15,38,25,34,14,180
Savannah GA,43,11,17,37,28,43,10,189
Pittsburgh PA,51,10,17,50,23,34,16,201
Ft. Wayne IN,42,4,14,50,15,25,15,165
Cleveland-Akron (Canton) OH,42,6,16,44,18,26,14,166
Washington DC (Hagerstown MD),47,5,15,33,15,46,11,172
Baltimore MD,51,9,18,44,18,44,16,200
Flint-Saginaw-Bay City MI,43,8,17,50,12,34,19,183
Buffalo NY,49,5,20,49,18,25,16,182
Cincinnati OH,45,6,18,43,17,25,15,169
Erie PA,53,14,17,50,25,43,8,210
Charlotte NC,43,7,16,39,21,29,16,171
Greensboro-High Point-Winston Salem NC,47,10,15,45,24,29,13,183
Charleston SC,55,14,20,42,16,23,15,185
Augusta GA,48,12,26,39,18,24,14,181
Providence RI-New Bedford MA,43,3,16,45,20,36,17,180
Columbus GA,41,7,17,46,25,33,14,183
Burlington VT-Plattsburgh NY,49,6,14,53,21,44,10,197
Atlanta GA,42,6,15,35,19,36,13,166
Colomn total,1164,191,415,1082,483,850,359,4544

In [11]:
edf=df1
x2=0

In [12]:
for i in range(7):
    for j in range(25):
        a=edf.iloc[-1][i]*edf.iloc[j][-1]/edf.iloc[-1][-1]
        edf.iloc[j,i]=a
        x2+=((df.iloc[j,i]-a)**2)/a

b
44
b
47.0
b
48.0
b
44.0
b
52.0
b
47.0
b
48.0
b
43.0
b
51.0
b
42.0
b
42.0
b
47.0
b
51.0
b
43.0
b
49.0
b
45.0
b
53.0
b
43.0
b
47.0
b
55.0
b
48.0
b
43.0
b
41.0
b
49.0
b
42.0
b
6
b
6.0
b
3.0
b
14.0
b
7.0
b
6.0
b
6.0
b
11.0
b
10.0
b
4.0
b
6.0
b
5.0
b
9.0
b
8.0
b
5.0
b
6.0
b
14.0
b
7.0
b
10.0
b
14.0
b
12.0
b
3.0
b
7.0
b
6.0
b
6.0
b
17
b
13.0
b
16.0
b
14.0
b
16.0
b
16.0
b
15.0
b
17.0
b
17.0
b
14.0
b
16.0
b
15.0
b
18.0
b
17.0
b
20.0
b
18.0
b
17.0
b
16.0
b
15.0
b
20.0
b
26.0
b
16.0
b
17.0
b
14.0
b
15.0
b
39
b
38.0
b
50.0
b
37.0
b
41.0
b
45.0
b
38.0
b
37.0
b
50.0
b
50.0
b
44.0
b
33.0
b
44.0
b
50.0
b
49.0
b
43.0
b
50.0
b
39.0
b
45.0
b
42.0
b
39.0
b
45.0
b
46.0
b
53.0
b
35.0
b
21
b
16.0
b
12.0
b
19.0
b
23.0
b
14.0
b
25.0
b
28.0
b
23.0
b
15.0
b
18.0
b
15.0
b
18.0
b
12.0
b
18.0
b
17.0
b
25.0
b
21.0
b
24.0
b
16.0
b
18.0
b
20.0
b
25.0
b
21.0
b
19.0
b
31
b
33.0
b
37.0
b
49.0
b
36.0
b
31.0
b
34.0
b
43.0
b
34.0
b
25.0
b
26.0
b
46.0
b
44.0
b
34.0
b
25.0
b
25.0
b
43.0
b
29.0
b
29.0
b
23.0
b
24.0
b
36.0
b
33.0
b
44.0
b
36.0
b
14
b
12.0
b
24.0
b
14.0
b
14.0
b
15.0
b
14.0
b
10.0
b
16.0
b
15.0
b
14.0
b
11.0
b
16.0
b
19.0
b
16.0
b
15.0
b
8.0
b
16.0
b
13.0
b
15.0
b
14.0
b
17.0
b
14.0
b
10.0
b
13.0

In [13]:
df

,2004+cancer,2004+cardiovascular,2004+stroke,2004+depression,2004+rehab,2004+vaccine,2004+diarrhea,Row total
dma,,,,,,,,
Portland-Auburn ME,44,6,17,39,21,31,14,172
New York NY,47,6,13,38,16,33,12,165
Binghamton NY,48,3,16,50,12,37,24,190
Macon GA,44,14,14,37,19,49,14,191
Philadelphia PA,52,7,16,41,23,36,14,189
Detroit MI,47,6,16,45,14,31,15,174
Boston MA-Manchester NH,48,6,15,38,25,34,14,180
Savannah GA,43,11,17,37,28,43,10,189
Pittsburgh PA,51,10,17,50,23,34,16,201
Ft. Wayne IN,42,4,14,50,15,25,15,165
Cleveland-Akron (Canton) OH,42,6,16,44,18,26,14,166
Washington DC (Hagerstown MD),47,5,15,33,15,46,11,172
Baltimore MD,51,9,18,44,18,44,16,200
Flint-Saginaw-Bay City MI,43,8,17,50,12,34,19,183
Buffalo NY,49,5,20,49,18,25,16,182
Cincinnati OH,45,6,18,43,17,25,15,169
Erie PA,53,14,17,50,25,43,8,210
Charlotte NC,43,7,16,39,21,29,16,171
Greensboro-High Point-Winston Salem NC,47,10,15,45,24,29,13,183
Charleston SC,55,14,20,42,16,23,15,185
Augusta GA,48,12,26,39,18,24,14,181
Providence RI-New Bedford MA,43,3,16,45,20,36,17,180
Columbus GA,41,7,17,46,25,33,14,183
Burlington VT-Plattsburgh NY,49,6,14,53,21,44,10,197
Atlanta GA,42,6,15,35,19,36,13,166
Colomn total,1164,191,415,1082,483,850,359,4544

In [14]:
df1

,2004+cancer,2004+cardiovascular,2004+stroke,2004+depression,2004+rehab,2004+vaccine,2004+diarrhea,Row total
dma,,,,,,,,
Portland-Auburn ME,44.059859,7.229754,15.708627,40.955986,18.282570,32.174296,13.588908,172
New York NY,42.266725,6.935519,15.069322,39.289173,17.538512,30.864877,13.035871,165
Binghamton NY,48.670775,7.986356,17.352553,45.242077,20.195863,35.541373,15.011004,190
Macon GA,48.926937,8.028389,17.443882,45.480194,20.302157,35.728433,15.090009,191
Philadelphia PA,48.414613,7.944322,17.261224,45.003961,20.089569,35.354313,14.931998,189
Detroit MI,44.572183,7.313820,15.891285,41.432218,18.495158,32.548415,13.746919,174
Boston MA-Manchester NH,46.109155,7.566021,16.439261,42.860915,19.132923,33.670775,14.220951,180
Savannah GA,48.414613,7.944322,17.261224,45.003961,20.089569,35.354313,14.931998,189
Pittsburgh PA,51.488556,8.448724,18.357174,47.861356,21.365097,37.599032,15.880062,201
Ft. Wayne IN,42.266725,6.935519,15.069322,39.289173,17.538512,30.864877,13.035871,165
Cleveland-Akron (Canton) OH,42.522887,6.977553,15.160651,39.527289,17.644806,31.051937,13.114877,166
Washington DC (Hagerstown MD),44.059859,7.229754,15.708627,40.955986,18.282570,32.174296,13.588908,172
Baltimore MD,51.232394,8.406690,18.265845,47.623239,21.258803,37.411972,15.801056,200
Flint-Saginaw-Bay City MI,46.877641,7.692121,16.713248,43.575264,19.451805,34.231954,14.457967,183
Buffalo NY,46.621479,7.650088,16.621919,43.337148,19.345511,34.044894,14.378961,182
Cincinnati OH,43.291373,7.103653,15.434639,40.241637,17.963688,31.613116,13.351893,169
Erie PA,53.794014,8.827025,19.179137,50.004401,22.321743,39.282570,16.591109,210
Charlotte NC,43.803697,7.187720,15.617298,40.717870,18.176276,31.987236,13.509903,171
Greensboro-High Point-Winston Salem NC,46.877641,7.692121,16.713248,43.575264,19.451805,34.231954,14.457967,183
Charleston SC,47.389965,7.776188,16.895907,44.051496,19.664393,34.606074,14.615977,185
Augusta GA,46.365317,7.608055,16.530590,43.099032,19.239217,33.857835,14.299956,181
Providence RI-New Bedford MA,46.109155,7.566021,16.439261,42.860915,19.132923,33.670775,14.220951,180
Columbus GA,46.877641,7.692121,16.713248,43.575264,19.451805,34.231954,14.457967,183
Burlington VT-Plattsburgh NY,50.463908,8.280590,17.991857,46.908891,20.939921,36.850792,15.564040,197
Atlanta GA,42.522887,6.977553,15.160651,39.527289,17.644806,31.051937,13.114877,166
Colomn total,1164.000000,191.000000,415.000000,1082.000000,483.000000,850.000000,359.000000,4544

In [17]:
dof=(len((df["2004+cancer"]))-2)*(len(df.iloc[0])-2)

In [18]:
dof

144

In [19]:
import scipy.stats as s

In [20]:
p=s.chi2.ppf(1-0.5,df=dof)

In [21]:
p

143.33388481577572

In [22]:
if(p<x2):
    print("dependent")
else:
    print("independent")

independent